"""Added new field

Revision ID: 29b9aa529c81
Revises: eb153141b922
Create Date: 2021-06-04 20:38:44.185835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b9aa529c81'
down_revision = 'eb153141b922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accepted_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_seat_details', sa.String(length=15), nullable=True))

    with op.batch_alter_table('denied_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_seat_details', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denied_requests', schema=None) as batch_op:
        batch_op.drop_column('actual_seat_details')

    with op.batch_alter_table('accepted_requests', schema=None) as batch_op:
        batch_op.drop_column('actual_seat_details')

    # ### end Alembic commands ###
