"""Added new fields

Revision ID: 67be4eaa866b
Revises: 29b9aa529c81
Create Date: 2021-06-04 20:45:31.830896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67be4eaa866b'
down_revision = '29b9aa529c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accepted_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_seat_details', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('to_seat_details', sa.String(length=15), nullable=True))
        batch_op.drop_column('actual_seat_details')

    with op.batch_alter_table('denied_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_seat_details', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('to_seat_details', sa.String(length=15), nullable=True))
        batch_op.drop_column('actual_seat_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denied_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_seat_details', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('to_seat_details')
        batch_op.drop_column('from_seat_details')

    with op.batch_alter_table('accepted_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_seat_details', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('to_seat_details')
        batch_op.drop_column('from_seat_details')

    # ### end Alembic commands ###
